collections:
  posts:
    output: true
    permalink: /news/:year-:month-:day-:title/
  videos:
    output: true

defaults:
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /:title/

plugins:
  - jekyll-mentions

exclude: [vendor, "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
include: ["_js"]
